remotedatabaseurl: "https://sdg.mango-solutions.com/data/____"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_json:
  - data: meta
    json: 'https://sdg.mango-solutions.com/data/____/meta/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://sdg.mango-solutions.com/data/____/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://sdg.mango-solutions.com/data/____/meta/schema.json'
  - data: reporting
    json: 'https://ONSdigital.github.io/sdg-data/stats/reporting.json'
  - data: translations
    # Pin to version of the translation repo
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.5.0.json'